### ISSUE TITLE
undocumented TODOs in package management 101

### ISSUE THREAD

**Issue by ruthgrace** [opsschool/curriculum#313]
Hi,
The document says:
"Creating packages
There are two todos here."
but I couldn't figure out what the two todos are from the to do list.
http://www.opsschool.org/en/latest/package_management_101.html
http://www.opsschool.org/en/latest/index.html?highlight=todo

**Comment by miketheman** [comment]
Hi @ruthgrace !
Thanks for pointing that out - I think I had a similar syntax issue https://github.com/opsschool/curriculum/commit/eef7f8dd92b3a69ee927c75e26aa567c8c71b352
Would you like to update these?

**Comment by ruthgrace** [comment]
fixed by #314
