### ISSUE TITLE
TODO List - issues and best practices

### ISSUE THREAD

**Issue by earthgecko** [opsschool/curriculum#88]
It occurs to me that it may be useful to "mirror" the TODO List in github issues and introduce it as a contributing note.  This will prevent contributors from working on the same TODO item, at the same time.

2 contributor submissions on 2 TODO List items is probably better than 2 contributions on 1 TODO List items.  At the moment to ensure that the TODO List is achieving the best possible MTR.

So for each item added to the TODO List a corresponding github issue would be raised for the item.  When someone wants to pickup a TODO they check the TODO issue on github and if not active make a comment saying "In progress ..."

I am happy to pick that up and do it if that makes sense, just update here.

I am going to put in into practice myself now :)

**Comment by miketheman** [comment]
Closing due to having a clear TODO list inside the rendered content which has been instrumental in people picking up what they want to work on.
